In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("newnews.csv")
data

Date                                           Headline  Tire  \
0    41:25.5                        England won 2019 world cup.     1   
1    48:35.1  Atletico Madrid won the spanish league this se...     1   
2    48:36.1       Manchester United won the Europa league 2021     5   
3    48:37.1                        Corona virus is irradicated     5   
4    48:38.1                 Lockdown to extend beyond June 1st     3   
..       ...                                                ...   ...   
327  53:52.1                                      claims report     2   
328  53:53.1                       warns against rush to reopen     1   
329  53:54.1        117 deaths; positivity rate falls to 1.53%      4   
330  53:55.1                diesel prices rise after day�s gap.     4   
331  53:56.1         Black Fungus Now Epidemic Disease in Delhi     4   

       review  
0        TRUE  
1        TRUE  
2        Fake  
3        Fake  
4    Not sure  
..        ...  
327      TRUE  
328      TRUE  
329      Fake  
330      Fake  
331      Fake  

[332 rows x 4 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Date      332 non-null    object
 1   Headline  332 non-null    object
 2   Tire      332 non-null    int64 
 3   review    332 non-null    object
dtypes: int64(1), object(3)
memory usage: 10.5+ KB


In [4]:
data.drop_duplicates()

Date                                           Headline  Tire  \
0    41:25.5                        England won 2019 world cup.     1   
1    48:35.1  Atletico Madrid won the spanish league this se...     1   
2    48:36.1       Manchester United won the Europa league 2021     5   
3    48:37.1                        Corona virus is irradicated     5   
4    48:38.1                 Lockdown to extend beyond June 1st     3   
..       ...                                                ...   ...   
327  53:52.1                                      claims report     2   
328  53:53.1                       warns against rush to reopen     1   
329  53:54.1        117 deaths; positivity rate falls to 1.53%      4   
330  53:55.1                diesel prices rise after day�s gap.     4   
331  53:56.1         Black Fungus Now Epidemic Disease in Delhi     4   

       review  
0        TRUE  
1        TRUE  
2        Fake  
3        Fake  
4    Not sure  
..        ...  
327      TRUE  
328      TRUE  
329      Fake  
330      Fake  
331      Fake  

[332 rows x 4 columns]

In [5]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
327    False
328    False
329    False
330    False
331    False
Length: 332, dtype: bool

In [6]:
data.columns

Index(['Date', 'Headline', 'Tire', 'review'], dtype='object')

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Headline"]=le.fit_transform(data["Headline"])
data.tail()

Date  Headline  Tire review
327  53:52.1        25     2   TRUE
328  53:53.1        54     1   TRUE
329  53:54.1         0     4   Fake
330  53:55.1        28     4   Fake
331  53:56.1         7     4   Fake

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["review"]=le.fit_transform(data["review"])
data.head()

Date  Headline  Tire  review
0  41:25.5       132     1       2
1  48:35.1        92     1       2
2  48:36.1       208     5       0
3  48:37.1       113     5       0
4  48:38.1       203     3       1

In [9]:
data['Tire']

0      1
1      1
2      5
3      5
4      3
      ..
327    2
328    1
329    4
330    4
331    4
Name: Tire, Length: 332, dtype: int64

In [10]:
data['times'] = pd.to_datetime(data.Date,format='%S:%M.%I').astype(np.int64)
data['times']

0     -2208969259000000000
1     -2208983052000000000
2     -2208982992000000000
3     -2208982932000000000
4     -2208982872000000000
              ...         
327   -2208982027000000000
328   -2208981967000000000
329   -2208981907000000000
330   -2208981847000000000
331   -2208981787000000000
Name: times, Length: 332, dtype: int64

In [11]:
data.at[2,'Date']

'48:36.1'

In [12]:
type(data.at[0,'times'])

numpy.int64

In [13]:
data=data[['Headline', 'Tire','times','review']]
data

Headline  Tire                times  review
0         132     1 -2208969259000000000       2
1          92     1 -2208983052000000000       2
2         208     5 -2208982992000000000       0
3         113     5 -2208982932000000000       0
4         203     3 -2208982872000000000       1
..        ...   ...                  ...     ...
327        25     2 -2208982027000000000       2
328        54     1 -2208981967000000000       2
329         0     4 -2208981907000000000       0
330        28     4 -2208981847000000000       0
331         7     4 -2208981787000000000       0

[332 rows x 4 columns]

In [14]:
data.describe()

Headline        Tire         times      review
count  332.000000  332.000000  3.320000e+02  332.000000
mean   163.144578    2.951807 -2.208983e+18    1.042169
std     93.694159    1.438811  1.302277e+12    0.898824
min      0.000000    1.000000 -2.208985e+18    0.000000
25%     81.750000    2.000000 -2.208984e+18    0.000000
50%    164.500000    3.000000 -2.208983e+18    1.000000
75%    247.250000    4.000000 -2.208982e+18    2.000000
max    320.000000    5.000000 -2.208969e+18    2.000000

In [15]:
x=data.iloc[:,0:-1]
x

Headline  Tire                times
0         132     1 -2208969259000000000
1          92     1 -2208983052000000000
2         208     5 -2208982992000000000
3         113     5 -2208982932000000000
4         203     3 -2208982872000000000
..        ...   ...                  ...
327        25     2 -2208982027000000000
328        54     1 -2208981967000000000
329         0     4 -2208981907000000000
330        28     4 -2208981847000000000
331         7     4 -2208981787000000000

[332 rows x 3 columns]

In [16]:
y=data.iloc[:,-1]
y

0      2
1      2
2      0
3      0
4      1
      ..
327    2
328    2
329    0
330    0
331    0
Name: review, Length: 332, dtype: int32

In [17]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(x,y, test_size = 0.2 , random_state = 2)

In [18]:
len(x_test)

265

In [19]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()

In [20]:
x_test = sd.fit_transform(x_test)
x_train = sd.fit_transform(x_train)

# linear regression

In [45]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([ 0.91313387,  0.39574091,  1.88740591,  0.41071701, -0.07821594,
        1.90076795,  1.89283801, -0.10647498,  1.42732761,  0.41390805,
        1.39375721, -0.10146703,  1.89034396, -0.07776451, -0.09354707,
        0.41252489, -0.07663696,  0.90422594,  1.89677316,  1.89760549,
        1.88697422, -0.10263651,  1.9251067 ,  1.90327676,  0.91614058,
       -0.09619761, -0.08307003,  1.40890871,  1.88387958,  0.41804079,
        0.88524228, -0.12405028,  0.87840613, -0.08215899,  1.90815767,
        0.91116037, -0.09632561,  0.41021422,  1.40160683,  0.41421719,
        0.40375624,  1.40978241,  0.92601788, -0.08145494,  0.89365919,
       -0.11206443,  1.39903085,  0.38018134,  1.40925988,  0.41688015,
       -0.0881379 ,  1.90490069,  1.9288057 ,  1.39375994,  0.40608393,
        1.38344392,  0.92488215,  0.41645731,  0.88482217,  1.92955197,
        0.38614868, -0.12275862,  1.89330947, -0.11575883,  1.9185335 ,
        0.92876323,  0.41594841,  1.40998367,  1.38477235,  0.91

In [22]:
testing_score = lr.score(x_test,y_test)
testing_score

0.6820273523271847

In [23]:
from sklearn.metrics import accuracy_score
sc1=accuracy_score(y_test, np.round(y_pred)) 
sc1

0.7320754716981132

In [24]:
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(y_test,y_pred)
print("MSC: ",mse1)

MSC:  0.25666924180820516


# logistic regression

In [25]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred1 = model.predict(x_test)
y_pred1

array([0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0,
       2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0,
       0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0,
       0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2,
       0, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 2, 1, 0, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 2, 2, 1, 0, 2, 1, 0, 2, 2, 2, 2,
       0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1,
       2, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2,
       0])

In [26]:
from sklearn.metrics import accuracy_score
sc2=accuracy_score(y_test, y_pred1) 
sc2

0.8

In [27]:
from sklearn.metrics import mean_squared_error
mse2 = mean_squared_error(y_test,y_pred1)
mse2

0.3471698113207547

# KNeighbors

In [28]:
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)
y_pred2= classifier.predict(x_test)
y_pred2

array([0, 0, 2, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0,
       2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0,
       0, 0, 2, 0, 2, 0, 0, 2, 2, 1, 0, 1, 1, 0, 1, 2, 0, 0, 2, 0, 2, 0,
       0, 1, 2, 0, 2, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 1, 0, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 0, 2, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 0, 0, 2, 0, 1, 2, 1, 1, 1, 0, 2, 0, 1, 1, 2, 2,
       0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 2, 2, 2,
       0, 1, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0,
       1, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1,
       1, 0, 0, 2, 0, 2, 1, 2, 0, 2, 2, 0, 0, 2, 2, 1, 1, 2, 1, 0, 2, 1,
       0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 2, 2, 2,
       0])

In [29]:
from sklearn.metrics import accuracy_score
sc3=accuracy_score(y_test, y_pred2) 
sc3

0.7358490566037735

In [30]:
from sklearn.metrics import mean_squared_error
mse4 = mean_squared_error(y_test,y_pred2)
mse4

0.41132075471698115

# Naive bayes-Gaussian

In [31]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
y_pred3 = nb.predict(x_test)
y_pred3

array([0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0,
       2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0,
       1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 1,
       0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 2, 1, 2, 0, 0, 2, 2,
       1, 2, 2, 1, 0, 2, 0, 0, 2, 1, 2, 2, 1, 1, 1, 0, 2, 0, 2, 2, 1, 2,
       0, 0, 0, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 2, 2, 2,
       0, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1,
       2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0,
       1, 2, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2,
       0])

In [32]:
from sklearn.metrics import accuracy_score
sc5=accuracy_score(y_test, y_pred3) 
sc5

0.8716981132075472

In [33]:
from sklearn.metrics import mean_squared_error
mse5 = mean_squared_error(y_test,y_pred2)
mse5

0.41132075471698115

# Naive bayes-Bernoulli

In [34]:
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train,y_train)
y_pred4 = model.predict(x_test)
y_pred4

array([0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0,
       2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0,
       0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0,
       0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2,
       0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2,
       0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0,
       0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0,
       2, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2,
       0])

In [35]:
from sklearn.metrics import accuracy_score
sc6=accuracy_score(y_test, y_pred4) 
sc6

0.7584905660377359

In [36]:
from sklearn.metrics import mean_squared_error
mse6 = mean_squared_error(y_test,y_pred4)
mse6

0.4

# RandomForest

In [37]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=20, criterion='gini',max_depth=5,max_features=3)
rfc.fit(x_train,y_train)
y_pred5 = rfc.predict(x_test)
y_pred5

array([1, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0,
       2, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0,
       1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 1, 0, 1, 2, 0, 0, 2, 0, 2, 1,
       1, 2, 2, 1, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 2, 0, 2, 0, 0, 2, 2,
       1, 2, 2, 1, 0, 2, 0, 0, 2, 1, 2, 2, 1, 1, 1, 0, 2, 0, 2, 2, 1, 2,
       0, 0, 0, 0, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2,
       0, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 2, 2, 0, 1, 0, 0, 2, 2, 0, 0, 0,
       1, 2, 1, 0, 1, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1,
       2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 0, 2, 1,
       1, 2, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 1, 1, 2, 2, 2, 2,
       0])

In [38]:
from sklearn.metrics import accuracy_score
sc7=accuracy_score(y_test, y_pred5) 
sc7

0.8905660377358491

In [39]:
from sklearn.metrics import mean_squared_error
mse7 = mean_squared_error(y_test,y_pred5)
mse7

0.24528301886792453

# xgboost

In [40]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [41]:
from xgboost import XGBClassifier
model1 = XGBClassifier()
model1.fit(x_train,y_train)
y_pred6 = model1.predict(x_test)
y_pred6

E:\jupiter\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[11:45:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


array([1, 0, 2, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0,
       2, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 0,
       1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 1,
       1, 2, 2, 1, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       2, 1, 0, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2, 2,
       0, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 2, 1, 1, 1, 0, 2, 0, 2, 2, 1, 2,
       0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2,
       0, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0,
       1, 2, 1, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1,
       2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 0, 2, 1,
       1, 2, 2, 0, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2,
       2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2, 2, 2,
       0])

In [42]:
from sklearn.metrics import accuracy_score
sc8=accuracy_score(y_test, y_pred6) 
sc8

0.8566037735849057

In [43]:
from sklearn.metrics import mean_squared_error
mse8 = mean_squared_error(y_test,y_pred6)
mse8

0.3132075471698113